[package]
name = "ws-mini-server"
version = "0.1.0"
edition = "2024"
license = { workspace = true }

[dependencies]
futures = "0.3.31"
tokio = { version = "1.44.2", features = ["full"] }
tokio-tungstenite = "0.26.2"
