[package]
name = "wsgator"
version = "0.1.0"
edition = "2024"
license = { workspace = true }

[dependencies]
async-trait = "0.1.88"
clap = { version = "4.5.37", features = ["derive"] }
futures = "0.3.31"
tokio = { version = "1.44.2", features = ["full"] }
tokio-tungstenite = "0.26.2"
